import { BadRequestException } from "@nestjs/common";
import { OrganizationDocumentSettingsService } from "./organization-document-settings.service";

describe("organization document settings rules", () => {
  it("creates default settings on first read", async () => {
    const prisma = {
      organizationDocumentSettings: {
        upsert: jest.fn().mockResolvedValue({
          id: "settings-1",
          organizationId: "org-1",
          invoiceTitle: "Tax Invoice",
          receiptTitle: "Payment Receipt",
          statementTitle: "Customer Statement",
          footerText: "Generated by LedgerByte",
          primaryColor: null,
          accentColor: null,
          showTaxNumber: true,
          showPaymentSummary: true,
          showNotes: true,
          showTerms: true,
          defaultInvoiceTemplate: "standard",
          defaultReceiptTemplate: "standard",
          defaultStatementTemplate: "standard",
        }),
      },
    };
    const service = new OrganizationDocumentSettingsService(prisma as never, { log: jest.fn() } as never);

    await expect(service.getOrCreate("org-1")).resolves.toMatchObject({
      invoiceTitle: "Tax Invoice",
      footerText: "Generated by LedgerByte",
    });
    expect(prisma.organizationDocumentSettings.upsert).toHaveBeenCalledWith({
      where: { organizationId: "org-1" },
      update: {},
      create: { organizationId: "org-1" },
    });
  });

  it("rejects invalid colors and templates on patch", async () => {
    const service = new OrganizationDocumentSettingsService({} as never, { log: jest.fn() } as never);

    await expect(service.update("org-1", "user-1", { primaryColor: "red" })).rejects.toThrow(BadRequestException);
    await expect(service.update("org-1", "user-1", { defaultInvoiceTemplate: "surprise" })).rejects.toThrow(BadRequestException);
  });

  it("maps settings into render settings", async () => {
    const prisma = {
      organizationDocumentSettings: {
        upsert: jest.fn().mockResolvedValue({
          invoiceTitle: "Commercial Invoice",
          receiptTitle: "Receipt",
          statementTitle: "Statement",
          footerText: "LedgerByte Footer",
          primaryColor: "#111827",
          accentColor: "#0f766e",
          showTaxNumber: false,
          showPaymentSummary: true,
          showNotes: false,
          showTerms: true,
          defaultInvoiceTemplate: "compact",
          defaultReceiptTemplate: "standard",
          defaultStatementTemplate: "detailed",
        }),
      },
    };
    const service = new OrganizationDocumentSettingsService(prisma as never, { log: jest.fn() } as never);

    await expect(service.invoiceRenderSettings("org-1")).resolves.toMatchObject({
      title: "Commercial Invoice",
      footerText: "LedgerByte Footer",
      primaryColor: "#111827",
      accentColor: "#0f766e",
      showTaxNumber: false,
      showNotes: false,
      template: "compact",
    });
  });
});
