export const ZATCA_XML_FIELD_MAPPING_STATUSES = ["IMPLEMENTED_LOCAL", "PLACEHOLDER", "NOT_STARTED", "NEEDS_OFFICIAL_VERIFICATION"] as const;

export type ZatcaXmlFieldMappingStatus = (typeof ZATCA_XML_FIELD_MAPPING_STATUSES)[number];

export interface ZatcaXmlFieldMappingItem {
  id: string;
  category: string;
  ledgerByteSource: string;
  xmlTarget: string;
  status: ZatcaXmlFieldMappingStatus;
  requiredForProduction: boolean;
  notes: string;
  officialVerificationRequired: boolean;
}

export const ZATCA_XML_FIELD_MAPPING = [
  {
    id: "invoice-header-number",
    category: "invoice-header",
    ledgerByteSource: "SalesInvoice.invoiceNumber",
    xmlTarget: "/Invoice/cbc:ID",
    status: "IMPLEMENTED_LOCAL",
    requiredForProduction: true,
    notes: "Local skeleton writes the LedgerByte invoice number. Official numbering constraints still need verification.",
    officialVerificationRequired: true,
  },
  {
    id: "invoice-header-uuid",
    category: "invoice-header",
    ledgerByteSource: "ZatcaInvoiceMetadata.invoiceUuid",
    xmlTarget: "/Invoice/cbc:UUID",
    status: "IMPLEMENTED_LOCAL",
    requiredForProduction: true,
    notes: "Generated and stored locally. Official UUID lifecycle rules need confirmation before production.",
    officialVerificationRequired: true,
  },
  {
    id: "invoice-header-issue-date-time",
    category: "invoice-header",
    ledgerByteSource: "SalesInvoice.issueDate",
    xmlTarget: "/Invoice/cbc:IssueDate and /Invoice/cbc:IssueTime",
    status: "IMPLEMENTED_LOCAL",
    requiredForProduction: true,
    notes: "Formatted deterministically from the invoice issue date. Timezone and source rules require official verification.",
    officialVerificationRequired: true,
  },
  {
    id: "invoice-header-type-code",
    category: "invoice-header",
    ledgerByteSource: "ZatcaInvoiceMetadata.zatcaInvoiceType",
    xmlTarget: "/Invoice/cbc:InvoiceTypeCode",
    status: "PLACEHOLDER",
    requiredForProduction: true,
    notes: "Local UBL type code scaffolding exists, but ZATCA Phase 2 invoice-type flags and subtype mapping are not final.",
    officialVerificationRequired: true,
  },
  {
    id: "supplier-party-name",
    category: "seller-supplier-party",
    ledgerByteSource: "ZatcaOrganizationProfile.sellerName",
    xmlTarget: "/Invoice/cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:RegistrationName",
    status: "IMPLEMENTED_LOCAL",
    requiredForProduction: true,
    notes: "Local profile value is emitted and escaped.",
    officialVerificationRequired: true,
  },
  {
    id: "supplier-party-vat",
    category: "seller-supplier-party",
    ledgerByteSource: "ZatcaOrganizationProfile.vatNumber",
    xmlTarget: "/Invoice/cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID",
    status: "IMPLEMENTED_LOCAL",
    requiredForProduction: true,
    notes: "Local VAT value is emitted and escaped. Official validation format still belongs to future ZATCA validation work.",
    officialVerificationRequired: true,
  },
  {
    id: "supplier-party-address",
    category: "seller-supplier-party",
    ledgerByteSource: "ZatcaOrganizationProfile address fields",
    xmlTarget: "/Invoice/cac:AccountingSupplierParty/cac:Party/cac:PostalAddress",
    status: "PLACEHOLDER",
    requiredForProduction: true,
    notes: "Local optional address fields are emitted when present. Required address fields and exact semantics need official verification.",
    officialVerificationRequired: true,
  },
  {
    id: "customer-party-name",
    category: "buyer-customer-party",
    ledgerByteSource: "Contact.displayName or Contact.name",
    xmlTarget: "/Invoice/cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:RegistrationName",
    status: "IMPLEMENTED_LOCAL",
    requiredForProduction: true,
    notes: "Local buyer/customer name is emitted and escaped.",
    officialVerificationRequired: true,
  },
  {
    id: "customer-party-vat",
    category: "buyer-customer-party",
    ledgerByteSource: "Contact.taxNumber",
    xmlTarget: "/Invoice/cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID",
    status: "PLACEHOLDER",
    requiredForProduction: true,
    notes: "Emitted when present. Standard vs simplified invoice buyer requirements need official verification.",
    officialVerificationRequired: true,
  },
  {
    id: "invoice-line-core-amounts",
    category: "invoice-lines",
    ledgerByteSource: "SalesInvoiceLine quantity, unitPrice, taxableAmount, taxAmount, lineTotal",
    xmlTarget: "/Invoice/cac:InvoiceLine",
    status: "IMPLEMENTED_LOCAL",
    requiredForProduction: true,
    notes: "Local line amounts are formatted deterministically. Official line-level tax category rules are not complete.",
    officialVerificationRequired: true,
  },
  {
    id: "tax-total-vat",
    category: "tax-totals",
    ledgerByteSource: "SalesInvoice.taxTotal",
    xmlTarget: "/Invoice/cac:TaxTotal",
    status: "IMPLEMENTED_LOCAL",
    requiredForProduction: true,
    notes: "Local VAT total skeleton is emitted. Multi-category and exempt/zero-rated breakdowns need official mapping.",
    officialVerificationRequired: true,
  },
  {
    id: "monetary-total",
    category: "monetary-totals",
    ledgerByteSource: "SalesInvoice taxableTotal, discountTotal, total",
    xmlTarget: "/Invoice/cac:LegalMonetaryTotal",
    status: "IMPLEMENTED_LOCAL",
    requiredForProduction: true,
    notes: "Local monetary totals are emitted with two decimals. Rounding and allowance/charge semantics need official verification.",
    officialVerificationRequired: true,
  },
  {
    id: "payment-settlement",
    category: "payment-settlement",
    ledgerByteSource: "Not yet mapped",
    xmlTarget: "/Invoice/cac:PaymentMeans and related settlement nodes",
    status: "NOT_STARTED",
    requiredForProduction: true,
    notes: "Payment means, settlement, and allowance/charge handling are intentionally not implemented yet.",
    officialVerificationRequired: true,
  },
  {
    id: "icv",
    category: "hash-icv",
    ledgerByteSource: "ZatcaInvoiceMetadata.icv",
    xmlTarget: "/Invoice/cbc:ID[@schemeID='ICV']",
    status: "PLACEHOLDER",
    requiredForProduction: true,
    notes: "Local ICV is emitted for hash-chain groundwork. Official XML placement and rules need confirmation.",
    officialVerificationRequired: true,
  },
  {
    id: "previous-invoice-hash",
    category: "hash-icv",
    ledgerByteSource: "ZatcaInvoiceMetadata.previousInvoiceHash",
    xmlTarget: "/Invoice/cac:AdditionalDocumentReference[cbc:ID='PIH']",
    status: "PLACEHOLDER",
    requiredForProduction: true,
    notes: "Local previous hash is emitted. Official canonical source and embedding rules need verification.",
    officialVerificationRequired: true,
  },
  {
    id: "signature-extensions",
    category: "signature-extensions",
    ledgerByteSource: "Not yet mapped",
    xmlTarget: "/Invoice/ext:UBLExtensions",
    status: "NOT_STARTED",
    requiredForProduction: true,
    notes: "Cryptographic stamp/signature and canonicalization are intentionally pending.",
    officialVerificationRequired: true,
  },
  {
    id: "zatca-ubl-extensions",
    category: "extensions",
    ledgerByteSource: "Not yet mapped",
    xmlTarget: "/Invoice/ext:UBLExtensions",
    status: "NEEDS_OFFICIAL_VERIFICATION",
    requiredForProduction: true,
    notes: "Current XML only includes local TODO comments. Official UBL extension namespaces and contents must be verified.",
    officialVerificationRequired: true,
  },
] as const satisfies readonly ZatcaXmlFieldMappingItem[];
