ALTER TYPE "DocumentType" ADD VALUE 'REPORT_GENERAL_LEDGER';
ALTER TYPE "DocumentType" ADD VALUE 'REPORT_TRIAL_BALANCE';
ALTER TYPE "DocumentType" ADD VALUE 'REPORT_PROFIT_AND_LOSS';
ALTER TYPE "DocumentType" ADD VALUE 'REPORT_BALANCE_SHEET';
ALTER TYPE "DocumentType" ADD VALUE 'REPORT_VAT_SUMMARY';
ALTER TYPE "DocumentType" ADD VALUE 'REPORT_AGED_RECEIVABLES';
ALTER TYPE "DocumentType" ADD VALUE 'REPORT_AGED_PAYABLES';
ALTER TYPE "DocumentType" ADD VALUE 'BANK_RECONCILIATION_REPORT';
