"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/lib/api";
import { useActiveOrganizationId } from "@/hooks/use-active-organization";
import { FixedAssetCategory, FixedAssetNav } from "@/components/fixed-assets/fixed-assets-page";
import { LedgerAlert, LedgerButton, LedgerFieldLabel, LedgerFormSection, LedgerInput, LedgerPage, LedgerPageBody, LedgerPageHeader, LedgerSelect } from "@/components/ui/ledger-system";

export default function NewFixedAssetPage() {
  const organizationId = useActiveOrganizationId(); const router = useRouter();
  const [categories, setCategories] = useState<FixedAssetCategory[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (organizationId) apiRequest<FixedAssetCategory[]>("/fixed-assets/categories").then(setCategories).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load categories.")); }, [organizationId]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); try { const created = await apiRequest<{ id: string }>("/fixed-assets", { method: "POST", body: { name: String(data.get("name")), categoryId: String(data.get("categoryId")), acquisitionDate: String(data.get("acquisitionDate")), inServiceDate: String(data.get("inServiceDate")), baseAcquisitionCost: String(data.get("baseAcquisitionCost")), baseSalvageValue: String(data.get("baseSalvageValue")), usefulLifeMonths: Number(data.get("usefulLifeMonths")), description: String(data.get("description") || "") || undefined } }); router.push(`/fixed-assets/${created.id}`); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create fixed asset."); } finally { setBusy(false); } }
  return <LedgerPage><LedgerPageHeader eyebrow="Accounting / Fixed assets" title="Add fixed asset" description="Create a draft record first. Review and capitalization are separate accounting actions." /><LedgerPageBody><FixedAssetNav />{error ? <LedgerAlert tone="danger" title="Could not create asset">{error}</LedgerAlert> : null}<form onSubmit={submit} className="space-y-4"><LedgerFormSection title="Asset identity" description="Use a stable operational name; the system assigns the asset number."><div><LedgerFieldLabel htmlFor="name">Asset name</LedgerFieldLabel><LedgerInput id="name" name="name" required placeholder="Dell Latitude 7440" /></div><div><LedgerFieldLabel htmlFor="categoryId">Category</LedgerFieldLabel><LedgerSelect id="categoryId" name="categoryId" required defaultValue=""><option value="" disabled>Select category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.code} · {category.name}</option>)}</LedgerSelect></div><div className="md:col-span-2"><LedgerFieldLabel htmlFor="description">Description</LedgerFieldLabel><LedgerInput id="description" name="description" placeholder="Finance team laptop" /></div></LedgerFormSection><LedgerFormSection title="Acquisition and depreciation" description="Monthly straight-line depreciation begins the month after the in-service date."><div><LedgerFieldLabel htmlFor="acquisitionDate">Acquisition date</LedgerFieldLabel><LedgerInput id="acquisitionDate" name="acquisitionDate" type="date" required /></div><div><LedgerFieldLabel htmlFor="inServiceDate">In-service date</LedgerFieldLabel><LedgerInput id="inServiceDate" name="inServiceDate" type="date" required /></div><div><LedgerFieldLabel htmlFor="baseAcquisitionCost">Base acquisition cost</LedgerFieldLabel><LedgerInput id="baseAcquisitionCost" name="baseAcquisitionCost" inputMode="decimal" required placeholder="1000.0000" /></div><div><LedgerFieldLabel htmlFor="baseSalvageValue">Base salvage value</LedgerFieldLabel><LedgerInput id="baseSalvageValue" name="baseSalvageValue" inputMode="decimal" defaultValue="0.0000" required /></div><div><LedgerFieldLabel htmlFor="usefulLifeMonths">Useful life (months)</LedgerFieldLabel><LedgerInput id="usefulLifeMonths" name="usefulLifeMonths" type="number" min="1" required placeholder="36" /></div></LedgerFormSection><div className="flex flex-wrap justify-end gap-2"><LedgerButton href="/fixed-assets" variant="secondary">Cancel</LedgerButton><LedgerButton type="submit" variant="primary" disabled={busy}>{busy ? "Saving draft…" : "Save draft"}</LedgerButton></div></form></LedgerPageBody></LedgerPage>;
}
