CREATE TYPE "DocumentType" AS ENUM ('SALES_INVOICE', 'CUSTOMER_PAYMENT_RECEIPT', 'CUSTOMER_STATEMENT');

CREATE TYPE "GeneratedDocumentStatus" AS ENUM ('GENERATED', 'FAILED', 'SUPERSEDED');

CREATE TABLE "OrganizationDocumentSettings" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "organizationId" UUID NOT NULL,
  "invoiceTitle" TEXT NOT NULL DEFAULT 'Tax Invoice',
  "receiptTitle" TEXT NOT NULL DEFAULT 'Payment Receipt',
  "statementTitle" TEXT NOT NULL DEFAULT 'Customer Statement',
  "footerText" TEXT NOT NULL DEFAULT 'Generated by LedgerByte',
  "primaryColor" TEXT,
  "accentColor" TEXT,
  "showTaxNumber" BOOLEAN NOT NULL DEFAULT true,
  "showPaymentSummary" BOOLEAN NOT NULL DEFAULT true,
  "showNotes" BOOLEAN NOT NULL DEFAULT true,
  "showTerms" BOOLEAN NOT NULL DEFAULT true,
  "defaultInvoiceTemplate" TEXT NOT NULL DEFAULT 'standard',
  "defaultReceiptTemplate" TEXT NOT NULL DEFAULT 'standard',
  "defaultStatementTemplate" TEXT NOT NULL DEFAULT 'standard',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "OrganizationDocumentSettings_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "GeneratedDocument" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "organizationId" UUID NOT NULL,
  "documentType" "DocumentType" NOT NULL,
  "sourceType" TEXT NOT NULL,
  "sourceId" TEXT NOT NULL,
  "documentNumber" TEXT NOT NULL,
  "filename" TEXT NOT NULL,
  "mimeType" TEXT NOT NULL DEFAULT 'application/pdf',
  "storageProvider" TEXT NOT NULL DEFAULT 'database',
  "storageKey" TEXT,
  "contentBase64" TEXT,
  "contentHash" TEXT NOT NULL,
  "sizeBytes" INTEGER NOT NULL,
  "status" "GeneratedDocumentStatus" NOT NULL DEFAULT 'GENERATED',
  "generatedById" UUID,
  "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "GeneratedDocument_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "OrganizationDocumentSettings_organizationId_key" ON "OrganizationDocumentSettings"("organizationId");

CREATE INDEX "GeneratedDocument_organizationId_idx" ON "GeneratedDocument"("organizationId");
CREATE INDEX "GeneratedDocument_organizationId_documentType_idx" ON "GeneratedDocument"("organizationId", "documentType");
CREATE INDEX "GeneratedDocument_organizationId_sourceType_sourceId_idx" ON "GeneratedDocument"("organizationId", "sourceType", "sourceId");
CREATE INDEX "GeneratedDocument_organizationId_status_idx" ON "GeneratedDocument"("organizationId", "status");
CREATE INDEX "GeneratedDocument_generatedById_idx" ON "GeneratedDocument"("generatedById");

ALTER TABLE "OrganizationDocumentSettings" ADD CONSTRAINT "OrganizationDocumentSettings_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GeneratedDocument" ADD CONSTRAINT "GeneratedDocument_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GeneratedDocument" ADD CONSTRAINT "GeneratedDocument_generatedById_fkey" FOREIGN KEY ("generatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
