import { buildDocumentSettingsPayload, isValidOptionalHexColor } from "./document-settings";

describe("document settings helpers", () => {
  it("normalizes optional colors to null", () => {
    const payload = buildDocumentSettingsPayload({
      invoiceTitle: " Tax Invoice ",
      receiptTitle: " Payment Receipt ",
      statementTitle: " Customer Statement ",
      footerText: " Generated by LedgerByte ",
      primaryColor: "",
      accentColor: " #0f766e ",
      showTaxNumber: true,
      showPaymentSummary: true,
      showNotes: true,
      showTerms: false,
      defaultInvoiceTemplate: "standard",
      defaultReceiptTemplate: "compact",
      defaultStatementTemplate: "detailed",
    });

    expect(payload.primaryColor).toBeNull();
    expect(payload.accentColor).toBe("#0f766e");
    expect(payload.invoiceTitle).toBe("Tax Invoice");
  });

  it("validates optional hex colors", () => {
    expect(isValidOptionalHexColor("")).toBe(true);
    expect(isValidOptionalHexColor("#111827")).toBe(true);
    expect(isValidOptionalHexColor("red")).toBe(false);
  });
});
